version: 1.0.{build}
skip_tags: true
image: Visual Studio 2019
configuration: release
platform: x64
before_build:
- git submodule update --init --recursive
- ps: tools\windows\premake5.exe vs2019
build:
  project: build/gsc-tool.sln
  verbosity: minimal
test: off
artifacts:
- path: build/bin/release/gsc-tool.exe
deploy:
- provider: GitHub
  auth_token:
    secure: AqZXWi1GBskqk/3nQeAlwGBHipNnAHT4g7D4dCIcCs4l9mHAiUTqKRmLgaCAnPI3
  on:
    branch: prod
